name: raincast
description: Aplikasi perkiraan hujan dengan Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0          # Untuk memanggil API Open-Meteo
  geolocator: ^12.0.0   # Untuk mendapatkan lokasi pengguna
  intl: ^0.19.0         # Untuk format tanggal dan waktu
  provider: ^6.1.0      # Untuk manajemen state
  flutter_map: ^7.0.0   # Untuk peta interaktif
  latlong2: ^0.9.1      # Untuk mengelola koordinat
  rename: ^3.0.2        # Untuk ganti nama & package aplikasi
  flutter_launcher_icons: ^0.13.1 # Untuk ganti logo aplikasi
  permission_handler: ^11.4.0 # Untuk menangani handling permission

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/raincast-logo.jpg
